### ISSUE TITLE
Improve FlashMatch error message

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbncode#102]
I got
<pre>
%MSG-s ArtException:  FlashPredict:fmatchREDO@Construction  26-Mar-2021 08:33:46 CDT ModuleConstruction
cet::exception caught in art
---- FatalRootError BEGIN
  Fatal Root Error: TFile::TFile
  file name is not specified
  ROOT severity: 3000
---- FatalRootError END
</pre>
which didn't give me very much to go on. It turns out the problem is I hadn't setup the `sbnd_data` product. It would be good to improve the message to something like
<pre>"the_flashmatch_file.root" not found in $FW_SEARCH_PATH</pre>
plus maybe some hint that this is likely about sbnd_data

**Comment by ikatza** [comment]
I'll look into it.

**Comment by ikatza** [comment]
Made a PR for this. Messages look like this now:

```
%MSG
%MSG-s ArtException:  FlashPredict:fmatch@Construction 26-Mar-2021 10:09:13 CDT  ModuleConstruction
cet::exception caught in art
---- FlashPredict BEGIN
  Could not find the light-charge match root file 'FlashMatch/fm_metrics_sbnd.root' on FW_SEARCH_PATH
---- FlashPredict END
%MSG
```


```
%MSG-s ArtException:  FlashPredict:fmatch@Construction 26-Mar-2021 10:01:53 CDT  ModuleConstruction
cet::exception caught in art
---- FlashPredict BEGIN
  The metrics file '/sbnd/data/FlashMatch/fm_metrics_sbnd.root'lacks at least one metric.
---- FlashPredict END
%MSG
```
