### ISSUE TITLE
Inconsistent units of energy in CAFMaker

### ISSUE THREAD

**Issue by ikatza** [SBNSoftware/sbncode#105]
I've noticed that the units of energy whenever dealing with a truth quantity are in **GeV**, whilst reconstructed quantities; and actually maybe only `rec.reco.slc.shw` are in **MeV**.

Not a deal breaker, but it's a minor nuisance that seems unnecessary to me.

**Comment by cjbackhouse** [comment]
My vote is strongly for GeV/cm/ns everywhere. We're literally about to produce files with the current code, so I think we will have to sit tight on this for a while.

**Comment by etyley** [comment]
My understanding is that this is largely inherited from the units that are used within LArSoft, so I guess it depends whether we want to main consistency between the `recob` and `SR` products or be consistent within the CAFs.

**Comment by cjbackhouse** [comment]
One benefit of having the additional CAF layer is that you can fix infelicities in the underlying art structures there, and most analyzers will be none-the-wiser.

What actual larsoft products are we talking about though? If they are in our control we should fix them, and if they're in larsoft proper we should at least attempt to argue for sanity.

**Comment by etyley** [comment]
For Iker's example, the `recob::Shower` in LArSoft uses `MeV` for the energy and `MeV/cm` for dE/dx.

**Comment by gputnam** [comment]
I agree with enforcing unit consistency -- we do this in a number of other places in CAFMaker already (lots of dividing or multiplying by 1000).

**Comment by etyley** [comment]
If the consensus is that unit consistency is the best way forward I will make the change. This will break many of the existing analysis scripts so will take a bit of time to get everyone up to date. I will bring this up in an upcoming CAF infrastructure meeting then get this done after the workshop.

**Comment by cjbackhouse** [comment]
@etyley I just saw this issue again. It's safely after the workshop now, can we make progress on this?

**Comment by etyley** [comment]
Sure I will crack on with making the sbncode changes now. There is a question about what we want to do in sbnana: if we make the change in the Cuts there then they will not work properly on the latest set of `official` CAFs. However, if we delay this anyone making their own CAFs will run into the same issue. Maybe we need to discuss the policy on these sorts of breaking changes in an upcoming analysis infrastructure meeting?

**Comment by cjbackhouse** [comment]
Yeah, I think the best you can really do is have the changes queued up, but only make them just before a new production to minimize the window for the worst confusion.

**Comment by etyley** [comment]
I will make a draft PR for sbnana for now then

**Comment by absolution1** [comment]
> For Iker's example, the `recob::Shower` in LArSoft uses `MeV` for the energy and `MeV/cm` for dE/dx.

Hey.
LArSoft is supposed to maintain a consistent set of units across the board.
dE/dx being in MeV/cm, while going against the grain, is sensible because it keeps the size of the numbers small.  And, like, everyone thinks of dE/dx as MeV/cm.

The recob::Showers should be changed in LArSoft if they aren't in consistent units.  In this specific instance, this is actually within our own remit to change.
@etyley, should we be putting in a PR to LArSoft for this?

**Comment by etyley** [comment]
I imagine that making this sort of breaking change to LArSoft would break a large amount of downstream code, but we can start a conversation with the relevant people?

**Comment by etyley** [comment]
I guess we could modify it there, but I am not a big fan of different modules (PandoraShower and EMShower) using the same object but with different units

**Comment by absolution1** [comment]
Fortunately PandoraShower doesn't reconstruct the energy, so that leaves EMShower.  I'd naively expect that changing EMShower's units would have a minimal impact as I'm not sure its used in many places across larsoft.  
Obviously I'm pulling this thread off on a tangent.  I think we should strike up a conversation with SciSoft about this.

**Comment by etyley** [comment]
I also made PRs to [sbnana](https://github.com/SBNSoftware/sbnana/pull/29) and [sbnanaobj](https://github.com/SBNSoftware/sbnanaobj/pull/18)
