### ISSUE TITLE
CAFMaker aborts if there are no weights present

### ISSUE THREAD

**Issue by gputnam** [SBNSoftware/sbncode#106]
In commit https://github.com/SBNSoftware/sbncode/commit/9659ce2230cdcb98827932f7900a925f21705a02, an explicit call to `abort` was added into CAFMaker if there are no weights present. 

This is a mistake -- CAFMaker is intended to fail gracefully if any data products are not present in the input file.

**Comment by cjbackhouse** [comment]
I'm confusing myself, because this code doesn't appear to exist in this form anymore.

We're now using an Assn rather than indices to do the matching.

**Comment by cjbackhouse** [comment]
https://github.com/SBNSoftware/sbncode/blob/develop/sbncode/CAFMaker/CAFMaker_module.cc#L757

**Comment by gputnam** [comment]
Ah, I see, I missed that. 

Ed had told me that there was an issue running CAFMaker over an event with no weights -- @etyley did I misdiagnose the issue? Is there something else going on?

**Comment by etyley** [comment]
There is still a `GetByLabelStrict` [here]. (https://github.com/SBNSoftware/sbncode/blob/1f6a5000741aff68fa6690adf42c706a79a3f2da/sbncode/CAFMaker/CAFMaker_module.cc#L350)

I retested this morning and running with `v09_19_00_01` I get the following error still:
```---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- ProductNotFound BEGIN
      Found zero products matching all selection criteria
        C++ type: std::vector<sbn::evwgh::EventWeightParameterSet>
        Module label: 'genieweight'
        Product instance name: ''
        Process name: (empty)The above exception was thrown while processing module CAFMaker/mycafmaker run: 40
    ---- ProductNotFound END
    Exception going through path runprod
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
```

**Comment by cjbackhouse** [comment]
I would argue that CAFMaker is working as designed - if you don't intend to have weights in the CAF, set the label to `""`. If you aren't sure / want best-effort, set `StrictMode: false`. I don't know why the weights should necessarily treated differently to any other product in this respect.

I thought the fix we were discussing on Thursday was that the weight calculator would put out an empty vector of weights when run on cosmics, which would keep CAFMaker happy. I will go and look at the other issue now.

**Comment by etyley** [comment]
Yeah, I think that a fcl change is all that is needed here to fix the workflow for files without the reweighting, which is all of the current MC production.  I don't really know which is the better solution as it would be great if the CAFMaker picked up the weights if available but turning off strict mode also affects all of the other products. I will leave it to people with more experience, and stronger opinions, to make that decision.

**Comment by gputnam** [comment]
Closing as a duplicate of https://github.com/SBNSoftware/sbncode/issues/107.
