### ISSUE TITLE
SBN Event Weight throws exception when running on cosmic-only sample.

### ISSUE THREAD

**Issue by etyley** [SBNSoftware/sbncode#107]
When running tests for the upcoming production I found that the event weight refused to run on a sample without neutrino interactions, meaning we must use separate workflows in the production, which was not the expected behaviour after discussion in the SBN analysis infrastructure meeting. The error was:
```%MSG-s ArtException:  PostEndJob 29-Mar-2021 03:23:51 CDT ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- ProductNotFound BEGIN
      Found zero products matching all selection criteria
        C++ type: std::vector<simb::MCTruth>
        Module label: 'generator'
        Product instance name: ''
        Process name: (empty)The above exception was thrown while processing module SBNEventWeight/genieweight run: 13 subRun: 42 event: 2
    ---- ProductNotFound END
    Exception going through path runprod
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
%MSG
```

**Comment by cjbackhouse** [comment]
I was thinking like this:
https://github.com/SBNSoftware/sbncode/compare/feature/evtwgt_cosmic

So you can either set the generator label to `""`, or if you want to run the same fcl over both genie and cosmics you can leave it set to "`generator`" but set the option to allow it to continue even if it doesn't find MCTruths.

I'm not proposing a merge just yet because I didn't quite understand the fcl structure. Where should I be writing that `AllowMissingTruth` exists, and writing a big comment about it?

**Comment by gputnam** [comment]
I want to add one other comment to this issue. On this point (from the other issue):

> I would argue that CAFMaker is working as designed - if you don't intend to have weights in the CAF, set the label to "". If you aren't sure / want best-effort, set StrictMode: false. I don't know why the weights should necessarily treated differently to any other product in this respect.

I disagree. The problem is that the large majority of times we run CAF, the input files don't contain systematic weights (even MC files). This isn't like a piece of reconstruction information that should always be present. Having a base configuration of the CAFMaker that fails over the majority of files is a problem -- we already saw issues with getting this to work for the workshop production.

I don't totally care what direction we take to fix this. We could have the weights label be `""` in the base config, and add in an extra weights config for running CAFMaker specifically on files that contain weights. Or we could have the code that grabs the weights fail gracefully. Either is fine with me.

**Comment by cjbackhouse** [comment]
> The problem is that the large majority of times we run CAF, the input files don't contain systematic weights

Is this going to be true going forwards? In the steady state I would naively expect the weights to be run just after the genie step, and then carried around in all the downstream files.

>  (even MC files)

We do definitely want to be able to run the regular configuration over data, or over cosmics. I was going to write that if there is no MCTruth we won't try to find weights for it, but I think that might not be true, and is something we can fix. For data, we need to not even try to look for the MCTruth. There is `evt.isRealData()`, but that can get pretty confused with overlays, so we might want to key off some other property of the files.

**Comment by wesketchum** [comment]
> Is this going to be true going forwards? In the steady state I would naively expect the weights to be run just after the genie step, and then carried around in all the downstream files.

Reweighting often needs to be done after initial generation, and so I would not assume that it will be done in an initial stage like this.

Side note: looping in @FernandaPsihas and @PetrilloAtWork so they can weight in on this.

**Comment by cjbackhouse** [comment]
One can always rerun the weights module after the fact if there are new configurations etc. I want to be in a world where it's generally safe to assume that systematic weights exist, so people can put error bands on plots in the general case, rather being some special big-effort thing that's only done specially for an oscillation analysis.

In fact, we should definitely add code to check that the genie version we are using to reweight matches what things were generated with. We tied ourselves in some terrible knots over this on NOvA.

**Comment by gputnam** [comment]
I don't know what the final steady state will be. But right now files almost never have systematic weights. And there are a bunch of types of simulations where gen weights don't make sense (cosmics, single-particle gen, certain BSM models). 

Systematic weights can also be very expensive -- both to run and to save on disk. Most current uses of CAFMaker don't require systematic uncertainties. So I would strongly advocate against including them as a default.

**Comment by cjbackhouse** [comment]
I put another commit on the same feature/evtwgt_cosmic branch that should help out in the cosmics/single particle/data case, but doesn't help in the case of neutrino simulation without weights
https://github.com/SBNSoftware/sbncode/commit/aedb741e02057e08919447d14a7e926c14416af4

**Comment by PetrilloAtWork** [comment]
> We do definitely want to be able to run the regular configuration over data, or over cosmics. I was going to write that if there is no MCTruth we won't try to find weights for it, but I think that might not be true, and is something we can fix. For data, we need to not even try to look for the MCTruth. There is `evt.isRealData()`, but that can get pretty confused with overlays, so we might want to key off some other property of the files.

"There is" also [`art::Event::experimentType()`](https://nusoft.fnal.gov/larsoft/doxsvn/html/classart_1_1EventAuxiliary.html#a8d92e398e001ae947f3161ec818b9511), which despite the name seems to indicate the [type of data](https://nusoft.fnal.gov/larsoft/doxsvn/html/classart_1_1EventAuxiliary.html#a3303dac9fa943e3d07b8fff9654775aa) in the event.
I would consider setting it correctly and then use it to characterise the overlay events too (there is no "overlay" value, but by the time SBN has any overlay _art_ may have implemented that if we ask to).
Drawback is that it is an `art::Event` member, and by the time you get a hold on it you have already declared what your module `produces()` (and `consumes()`). It's more likely to be used for a consistency check with the FHiCL configuration than to take a decision.

The careful reader will notice that this does not help a bit with the question on how to manage the absence of weights.

**Comment by mastbaum** [comment]
@cjbackhouse's solution of checking existing of `MCTruth` in the producer module looks reasonable to me, and at least for now making weights a best effort thing where downstream code will handle their absence gracefully. The new `AllowMissingTruth` parameter should go in the parameter set for the module, e.g. here: https://github.com/SBNSoftware/sbncode/blob/feature/evtwgt_cosmic/sbncode/SBNEventWeight/jobs/genie/eventweight_genie3_sbn_A.fcl#L16. FWIW, for the history of `EventWeight` it's just assumed GENIE events as input, and only been run over GENIE samples in production, which I think led to the mismatch in expectations here. But I think(?) we are heading toward a more generic RW module that just generates weights appropriate to the events it's handed, if any, which sounds like a nice solution.

> In fact, we should definitely add code to check that the genie version we are using to reweight matches what things were generated with. We tied ourselves in some terrible knots over this on NOvA.

In the `GenieWeightCalc`, I did add some checks that this event is (a) of beam neutrino origin, (b) GENIE is the generator, and (c) the tune name, if available, matches the currently-configured GENIE tune (i.e. `${GENIE_XSEC_TUNE}`): https://github.com/SBNSoftware/sbncode/blob/develop/sbncode/SBNEventWeight/Calculators/CrossSections/GenieWeightCalc.cxx#L232-L250. `simb::MCGeneratorInfo::generatorVersion` has the generator version as a string; that should also be checked here (but I think it needs to be reformatted to match `$GENIE_VERSION`).

**Comment by cjbackhouse** [comment]
See https://github.com/SBNSoftware/sbncode/pull/110 for the fixes proposed above, plus some other fcl changes that help with this problem.

What is the right thing to do with some of the other discussion here? Make new issue capturing the points?

**Comment by wesketchum** [comment]
I agree with making new issues that capture the other points not covered by #110
