### ISSUE TITLE
Quiet down SBNEventWeight

### ISSUE THREAD

**Issue by cjbacchus** [SBNSoftware/sbncode#109]
There are a large number of `INFO` and `NOTICE` messages printed out, especially at startup.

Tips for how to quiet things from @candreop

> The thresholds for all GENIE message streams can be overwritten.
The default settings are here: https://github.com/GENIE-MC/Generator/blob/master/config/Messenger.xml
Many GENIE apps provide a --message-thresholds argument to override this. If, within LArSoft, one couples to GENIE classes directly, somewhere at initialisation can do something like:
Messenger * m = Messenger::Instance();
bool ok = m->SetPrioritiesFromXmlFile(“/blah/some/file.xml”);

and @ikatza

> A while ago I had a go at changing the messaging levels in GENIE when it’s coupled to LArSoft.
The messenger is set in:
nugen/nugen/EventGeneratorBase/GENIE/GENIEHelper.cxx::StartGenieMessenger()
Note that’s not larsoft proper.
Looking at the code it seems that for GENIE versions prior to 2.9.0 there was some environmental variables… but right now is > hardcoded to Messenger_Whisper.xml
`2849 #if __GENIE_RELEASE_CODE__ >= GRELCODE(2,9,0)`
` 2850       std::string newval = "Messenger_whisper.xml";`
` 2851 #else`
` 2852       std::string newval = "Messenger_production.xml";`
` 2853 #endif`
https://nusoft.fnal.gov/larsoft/doxsvn/html/classevgb_1_1GENIEHelper.html#a8ede32516f70e607ec0ccc47742f567c

It sounds like we should add similar lines to the SBNEventWeight module, and a .xml file where they can be configured.

**Comment by wesketchum** [comment]
@mastbaum I know lots of other relevant work here, but any progress on this? Or can be shifted to another issue?

**Comment by wesketchum** [comment]
@mastbaum any progress on this?
