### ISSUE TITLE
Update sbncode to current larsoft/sbndcode/icaruscode version

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbncode#11]
Today it is `v08_57_00`.

**Comment by PetrilloAtWork** [comment]
This is related to issue SBNSoftware/sbnobj#3.

**Comment by PetrilloAtWork** [comment]
My work of moving dependencies spun off a SBNSoftware/sbncode updated to LArSoft version `v08_57_00`.
Branches are `feature/repositoryRestructuring` in both `sbnobj` and `sbncode`.

**Comment by PetrilloAtWork** [comment]
This needs to be repeated for the final "target" version.

**Comment by wesketchum** [comment]
Done. Closing.
