### ISSUE TITLE
Consider a continuous integration test system for sbncode

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbncode#12]
A continuous integration system _might_ be useful for `sbncode` itself.

We need to figure out what would be the content of the integration tests, which may be at different levels, e.g.:
* no actual test, but just a way to make sure the code still compiles
* minimal unit tests (e.g. for data products and libraries)
* actual tests

Contact people for the infrastructure are @vitodb (SBND) and [Vladimir Podstavkov](mailto:podstvkv@fnal.gov).
Deciding on the content is to us.

**Comment by PetrilloAtWork** [comment]
@vitodb Can we set up the C.I. building and unit test infrastructure?
Remind us what you need to know and what we need to do in order to get there.
The idea is to have a workflow able to build `larsoft` → (`sbnobj` + `sbncode`) [`feature/repositoryRestructuring` branch] → `icaruscode` / `sbndcode`

`icaruscode` / `sbndcode` may be on two different workflows or one, as it's more convenient — I would start with only `icaruscode` for simplicity, and when it works I would add `sbndcode` into that workflow or as a twin workflow.

In the future, `sbnanalysis` (or similar) may be appended to the end of a unified workflow, but we are not there yet.

**Comment by vitodb** [comment]
@PetrilloAtWork sure, we can start to set up the infrastructure for such CI build.
As you suggested, for now let's start with `icaruscode`.

The workflow that you describe is
`larsoft` → `(sbnobj + sbncode) [feature/repositoryRestructuring branch]` → `icaruscode`
Does this means that `sbnobj` and `sbncode` depend on `larsoft`
and
`icaruscode` depends on `sbnobj` and `sbncode` ?

As starting point to test this workflow does it make sense to report status for `(sbnobj + sbncode)`  and for `icaruscode` in the ICARUS CI dashboard, but using different builds rows?

**Comment by PetrilloAtWork** [comment]
Actually, `icaruscode` probably depends only on `sbncode`, which in turn depends on `sbnobj`. But I don't think it makes too much of a difference at this point.

I am not sure about the "build rows" — if I guess right, you refer to an `icaruscode` build being shown (and, I suppose, executed) as a `sbncode` build (one row in the dashboard report) followed by a `icaruscode` build (in its own row, and using a special workflow). In that case, I agree; I would agree also to a single row combining the two steps, but I can imagine that they would have to be split anyway sooner or later.

**Comment by vitodb** [comment]
OK, so, with the sake to build up this new workflow in atomic steps, I'll start to set up a workflow that:
1. checkout/build/test `LArSoft`
2. checkout/build/test `sbnobj` + `sbncode` + `icaruscode` (using LArSoft built in the previous step)
     I'll use the same MRB build area for those three packages and I'll report their status in the same CI dashboard row.

Now looking at  `sbnobj` and `sbncode` repos I see the following:
- last `sbncode` version is  v08_47_00
- for `sbnobj` I see it has only version v08_55_00

Do you know if those two versions are consistent?
Then, which `icaruscode` version is supposed to work with those?

**Comment by vitodb** [comment]
When doing some test with `sbnobj` + `sbncode` + `icaruscode`, I'm in the impression that `sbncode` brings in a dependency on
`sbndcode`, `uboonecode`, `icaruscode` and `ubcore`
Do I read this correctly from the following link to `sbncode` product_deps?
https://github.com/SBNSoftware/sbncode/blob/develop/ups/product_deps#L36

**Comment by PetrilloAtWork** [comment]
The only branch I am aware of that is set up consistently is `feature/repositoryRestructuring`.
In particular, `develop` has the old dependencies.

**Comment by vitodb** [comment]
Given your initial comment today I thought `feature/repositoryRestructuring` was the branch to look at, but I was not able to find it for `sbnobj` or `sbncode`, so I started with `develop`.
Have been that branch pushed to the repo?

**Comment by PetrilloAtWork** [comment]
Heh, good point. They are published _in my forked repositories_...
I have pushed them `upstream` (i.e. to SBNSoftware now). Except that I am not authorised to push into `sbndcode`.

This is an interesting topic... how does, for example, _LArSoft_ handle C.I. tests to branches? as far as I know, pushing branches to LArSoft official repositories is not allowed.

**Comment by vitodb** [comment]
OK, this makes a lot of sense and I realize why I was not able to find those branches. 

The C.I. has two mechanisms to deal with users branches on GitHub repositories through the `--revisions` option:
1. users can open a PR against the upstream repository, the C.I. can pick up the PR with a syntax like `Org/repo#PR`, where `Org` is the GitHub organization hosting the repository;
2. the C.I. can access branches from a fork using the syntax `user/repo1>repo2@branch`, where `user` is the user GitHub account hosting in the `repo1` the fork of `repo2`, which is the name of the repository that the C.I. expects to checkout the code. 

Now that `feature/repositoryRestructuring` is available on SBNSoftware I'll use it from here, though I see that `sbncode` still depends on `uboonecode`, so I'm not sure my test will work without pulling in also `uboonecode`.
I'll keep you posted tomorrow after I'll trigger my test.

**Comment by vitodb** [comment]
Indeed when I try to build `sbnobj` + `sbncode` + `icaruscode` the command `mrbsetenv` complains about `uboonecode`
https://dbweb6.fnal.gov:8443/TestCI/app/storage/docs/2020/08/04/buildSBNICARUS.log

Am I supposed to source uBooNE setup script so we can pull in `uboonecode`? Or I'm missing something else?

**Comment by PetrilloAtWork** [comment]
You will need to set up MicroBooNE CVMFS area. I haven't removed MicroBooNE dependencies.
We are talking about `/cvmfs/uboone.opensciencegrid.org/products/setup`.

**Comment by PetrilloAtWork** [comment]
For the record, I have opened issue #14 about MicroBooNE code dependency. I vaguely remember it was not superfluous.

**Comment by vitodb** [comment]
I moved a bit forward, but it looks like the build stage requires `sbndcode`
> 333: CMake Error at /cvmfs/larsoft.opensciencegrid.org/products/cetbuildtools/v7_15_01/Modules/FindUpsPackage.cmake:116 (message):
> 334:   SBNDCODE has not been setup
> 335: Call Stack (most recent call first):
> 336:   sbncode/CMakeLists.txt:54 (find_ups_product)

(full build log is available here: https://dbweb6.fnal.gov:8443/TestCI/app/storage/docs/2020/08/04/buildSBNICARUS%23xIRwYpE.log)

For now I'll include in this test CI build also `sbndcode` (branch `feature/repositoryRestructuring` that I see you have pushed to SBNSoftare)

**Comment by vitodb** [comment]
I made some progress, the build is successful but I get unit test failures:
https://dbweb6.fnal.gov:8443/TestCI/app/view_builds/index?offset=0&builds=icarus_ci%2F927&builds=

the two unit test [failing](https://dbweb6.fnal.gov:8443/TestCI/app/build_detail/phase_details?build_id=icarus_ci/927&platform=Linux%203.10.0-1127.el7.x86_64&phase=unit_test&buildtype=slf7%20e19:prof)  seem to belong to `sbndcode` and they are complaining about:
> 19:   ---- Configuration BEGIN
> 20:     Field response file 'Response/sbnd_response_v1.0.root' not found in FW_SEARCH_PATH
> 21:   ---- Configuration END

Do you happen to know if in the build I should include some other package? 
Currently I built: `sbnobj sbncode icaruscode sbndcode`

**Comment by PetrilloAtWork** [comment]
It looks like `sbnd_data` is [not set up](https://dbweb6.fnal.gov:8443/TestCI/app/storage/docs/2020/08/04/buildSBNICARUS%23QuYddx8.log) (note line 151).
Are you setting up SBND UPS?

**Comment by PetrilloAtWork** [comment]
To be explicit: in my local configuration I have to set up UPS areas for LArSoft, ICARUS, SBND _and_ MicroBooNE.

**Comment by vitodb** [comment]
Thanks for drive me through this :)
I made some more steps forward and I was able to run [integration tests](https://dbweb6.fnal.gov:8443/TestCI/app/build_detail/phase_details?build_id=icarus_ci/929&platform=Linux%203.10.0-1127.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof), (only ICARUS ones) but some are failing.
Looking at logs it looks like some libraries from MicroBooNE interfere with ICARUS libraries.
Not sure how we want to proceed from here.

**Comment by PetrilloAtWork** [comment]
Well, they are not more failing than the regular ICARUS ones, are they?
The main problem is that quick tests use reference files from the previous stage as input. The reference files are old, outdated and refer to an old geometry. The cosmics + neutrino jobs detect the discrepancy, try to load the old geometry, and fail (mostly because [the whole feature is flawed](https://cdcvs.fnal.gov/redmine/issues/24328)). The single particle jobs use as reference an old file, generated before the fix on `SingleGen` that makes it conforming to the other LArSoft event generation modules by adding the information of which geometry was used to build it. So, no geometry information, no check, no reload, everything is happiness except that in the end the reference files make no sense and describe a detector with 40k wires instead of 55k.
So I would say I expect the failures I see, not your fault, and also this is a reminder of how charming it is to work with an outdated C.I. test suite. Courtesy of ICARUS (this time).

**Comment by vitodb** [comment]
Maybe you are right that some failures for ICARUS CI test suite are expected, but the failure mode let's me think that the failure will not be fixed after ICARUS CI test suite and reference files will be updated.
The failure mode for `[single_reco_quick_test_icaruscode](https://dbweb6.fnal.gov:8443/TestCI/app/storage/docs/2020/08/04/stdout%23HpCzq7v.log)` 
> 69: ---- Configuration BEGIN
> 70:   make_tool: 
> 71:   ---- Configuration BEGIN
> 72:     UnknownPlugin
> 73:     ---- Configuration BEGIN
> 74:       Library specification "ROIFinderMorphological" corresponds to multiple libraries:
> 75:       /cvmfs/uboone.opensciencegrid.org/products/ubevt/v08_56_00/slf7.x86_64.e19.prof/lib/libROIFinderMorphological_tool.so
> 76:       /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/SBNICARUS/localProducts_SBNICARUS_SBNICARUS_lar_ci_e19_prof/icaruscode/v08_57_00/slf7.x86_64.e19.prof/lib/libicaruscode_TPC_SignalProcessing_RecoWire_DeconTools_ROIFinderMorphological_tool.so
> 77:     ---- Configuration END
> 78:     Plugin ROIFinderMorphological with version Unknown was not registered.
> 79:     Perhaps your plugin type is misspelled or is not a plugin recognized by this
> 80:     system.
> 81:   ---- Configuration END
> 82:   Exception caught while processing plugin spec: ROIFinderMorphological
> 83: ---- Configuration END

This looks to me as library clashing between ICARUS and MicroBooNE.

In the meantime I also triggered a CI build that, alongside the ICARUS CI test suite, ran the SBND CI test suite, here [results](https://dbweb6.fnal.gov:8443/TestCI/app/build_detail/phase_details?build_id=icarus_ci/930&platform=Linux%203.10.0-1127.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof) looks better.

**Comment by PetrilloAtWork** [comment]
_**groan**_
Yes, need to fix that.

**Comment by PetrilloAtWork** [comment]
Pull request #51 of `icaruscode` should fix that.

**Comment by PetrilloAtWork** [comment]
With @vitodb we have decided to import (`cherry-pick`) that fix in the branch we are using for the C.I. test (`feature/repositoryRestructuring`).
"I claim it should workⓇ".

**Comment by vitodb** [comment]
With the last update to `feature/repositoryRestructuring` branch of `icaruscode` the previous issue is gone, but a new library clash shows up for [single_reco_quick_test_icaruscode](https://dbweb6.fnal.gov:8443/TestCI/app/storage/docs/2020/09/08/stdout%23XIYAknh.log) and similarly for [nucosmics_reco_quick_test_icaruscode](https://dbweb6.fnal.gov:8443/TestCI/app/storage/docs/2020/09/08/stdout%23qcWCOPh.log)

For convenience the relevant excerpt of the log is below:

> 67: %MSG-s ArtException:  Decon1DROI:decon1DroiTPC0@Construction  08-Sep-2020 15:38:14 CDT ModuleConstruction
68: cet::exception caught in art
69: ---- Configuration BEGIN
70:   make_tool: 
71:   ---- Configuration BEGIN
72:     UnknownPlugin
73:     ---- Configuration BEGIN
74:       Library specification "BaselineMostProbAve" corresponds to multiple libraries:
75:       /cvmfs/uboone.opensciencegrid.org/products/ubevt/v08_56_00/slf7.x86_64.e19.prof/lib/libBaselineMostProbAve_tool.so
76:       /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/SBNICARUS/localProducts_SBNICARUS_SBNICARUS_lar_ci_e19_prof/icaruscode/v08_57_00/slf7.x86_64.e19.prof/lib/libicaruscode_TPC_SignalProcessing_RecoWire_DeconTools_BaselineMostProbAve_tool.so
77:     ---- Configuration END
78:     Plugin BaselineMostProbAve with version Unknown was not registered.
79:     Perhaps your plugin type is misspelled or is not a plugin recognized by this
80:     system.
81:   ---- Configuration END
82:   Exception caught while processing plugin spec: BaselineMostProbAve
83: ---- Configuration END
84: %MSG
85: Art has completed and will exit with status 9.

**Comment by PetrilloAtWork** [comment]
I have updated `feature/repositoryRestructuring`. _Again_.
You have no excuse now!
(I finally surrendered and run `test_runner` locally)

**Comment by vitodb** [comment]
That extra effort to use `test_runner` payed out.
Now ICARUS CI tests for `feature/repositoryRestructuring` within `sbncode` environment give the same results of ICARUS CI tests standalone.
Results are available [here](https://dbweb6.fnal.gov:8443/TestCI/app/view_builds/index?offset=0&builds=icarus_ci%2F1058&builds=) in the `icarus_ci/1058` CI build.

**Comment by PetrilloAtWork** [comment]
Great!
Can a SBND (`sbndcode`) workflow be set up in the same way?
I think that is the last thing we need for this part of the test.

**Comment by vitodb** [comment]
In the current CI workflow configuration we tests `sbncode`, `icaruscode`, `sbndcode` and `sbnobj` 
in the same environment.
And CI tests for  `icaruscode` and `sbndcode` are exercised.
So I think we are there.

**Comment by PetrilloAtWork** [comment]
Thank you a lot, @vitodb.
