### ISSUE TITLE
Rationalize NonRes weights output from SBNEventWeight

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbncode#138]
Currently, NonRes weights are saved in fewer combinations than we want physically, and then analysis code has to assign them to different event classes manually. This causes no end of complexity (see https://github.com/SBNSoftware/sbnana/blob/develop/sbnana/CAFAna/Systs/SBNWeightSysts.cxx#L161 for the kind of thing we're doing). I think it would be much better to save the actual systs we want into the files, so analysers can use them without thinking. Superficially this multiplies the number of NonRes weights by 4, but since 3/4 of them will be 1 in any one event, I think with any reasonable behaviour of ROOT compression there should be no observable effect on file size.

This seems a simple enough fix for a big win that I'd be willing to have a crack at it myself. But maybe it's not as simple as I think? How deeply buried is the weight logic? Will we disrupt other experiments? @mastbaum ?

**Comment by wesketchum** [comment]
@Ooohu is your work addressing this issue as well? If so link in a PR?

Looping in @mroda88 and @candreop here as well.

**Comment by Ooohu** [comment]
> @Ooohu is your work addressing this issue as well? If so link in a PR?
> 
> Looping in @mroda88 and @candreop here as well.

Yes, new GENIE weight in SBNEventWeight module will further breakdown non-resonant knobs into a finer categories such that more combinations of non-resonant knob is available.

see line 11~26 here: ( https://docs.google.com/spreadsheets/d/1G3dgVru-o4cUEHRWfnCUixhXGmjGPob1K5f--3GEcHc/edit#gid=0 )
