### ISSUE TITLE
BNB full osc fhicl configs

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbncode#155]
Need "full osc" fhicl configs for SBND and ICARUS. May be more appropriate in sbndcode and icaruscode, but putting issue here as placeholder.

**Comment by jzennamo** [comment]
SBND configuration: 
https://github.com/SBNSoftware/sbndcode/pull/135

**Comment by jzennamo** [comment]
@cfarnese pointed me to the correct ICARUS files, I will be putting these together today

**Comment by jzennamo** [comment]
ICARUS configurations:
https://github.com/SBNSoftware/icaruscode/pull/223

**Comment by jzennamo** [comment]
Once these are merged this can be closed

**Comment by wesketchum** [comment]
Both merged. Closing.
