### ISSUE TITLE
Investigate multiple SCE collections in new LArG4

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbncode#160]
Prompted by a presentation from @marcodeltutto , my understanding in the new larg4 is that there are two sim edep collections saved: one SCE shifted, one not, to properly handle inputs to photon and electron propagation.

I highly suspect this is non-optimal. We should:
* investigate if that's truly not optimal
* If so, modify workflows to reduce this need (e.g. electron drift module should just shift edeps within that module?)

This is a placeholder issue: it may be more appropriately moved/linked to an issue in LArSoft code.

**Comment by jzennamo** [comment]
I think this was resolved in https://github.com/SBNSoftware/sbndcode/pull/195, @marcodeltutto feel free to close this if you think it is done

**Comment by wesketchum** [comment]
I'll agree that we can close this.

**Comment by marcodeltutto** [comment]
Sorry I missed your message @jzennamo. I was keeping this open because we still have more than one SimEnergyDeposit collections. No longer related to SCE, but I was using this issue as a reminder. I'll open a new one.
