### ISSUE TITLE
Refactor CAFMaker fcls & move to sbndcode 

### ISSUE THREAD

**Issue by FernandaPsihas** [SBNSoftware/sbncode#170]
Move the existing sbnd CAFMaker fcls to sbndcode and refactor any configurations that are common to icarus and sbnd, which can be left on sbncode.

**Comment by wesketchum** [comment]
@pgreen135 @gputnam @FernandaPsihas has this been done? I somehow recall seeing a branch that did this, but may be mistaken.

**Comment by wesketchum** [comment]
@pgreen135 @PetrilloAtWork @FernandaPsihas did this get done?

**Comment by PetrilloAtWork** [comment]
I am proposing this to be done as the last step, given that many changes are occurring at the same time and moving things between repositories will bypass GIT merging ability.
As for the checks, if everything works _before_ the refactoring, to test the refactoring it should be enough to verify that:
1. the code runs
2. the final FHiCL configuration (`fhicl-dump`) for CAF making is the same as before the refactoring

**Comment by PetrilloAtWork** [comment]
@Ooohu Please inform us in this issue when #176 is completed, so that this one can proceed.

**Comment by wesketchum** [comment]
#176 is now merged.

**Comment by Ooohu** [comment]
One minor fix on the local FHiCL under SBNEventWeight Module is needed for finding the correct path of files mentioned in #189;  however, this is independent to the CAFMaker fcls.

**Comment by FernandaPsihas** [comment]
ok, then I think @jacoblarkin is good to go on this?

**Comment by jacoblarkin** [comment]
I have local branches on sbndcode and sbncode with the cafmaker fcls moved to sbndcode. It seems to work so I will make pull requests for those later today.

Who are the appropriate people to list as reviewers on sbncode and sbndcode?

For the refactoring part, there doesn't actually seem to be much opportunity for moving common configurations between sbnd and icarus. It looks like only the event weights, and the TacksMCS and TrackRange producers are shared between the two. Even for those last two, icarus splits the producers between the two cryostats so this wouldn't even reduce the customization in the icarus fcl.

**Comment by FernandaPsihas** [comment]
I would add Gray and Chris Backhouse as well as Gianluca and/or me as reviewers. I think refactoring what you can for now is ok, later there may be more so it is good to have a place for common vs detector specific configurations.
