### ISSUE TITLE
Create/setup sbnobj repository

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbncode#2]
Need an sbn object repository for sbn-specific objects to be added. `sbncode` should depend on it.

**Comment by cjbackhouse** [comment]
Does this just entail creating the repository within github/SBNSoftware and then moving relevant pieces over?

Oh, and getting it added to the build procedure (who do we ask about this?). Where will it be installed? Presumably the new SBN CVMFS area?

I see this pattern of splitting objects out into a seperate products in various places. Is there somewhere I can read about the rationale for it?

**Comment by cjbackhouse** [comment]
The ticket is RITM0975699 (so I can find it again without trawling through my emails).

**Comment by wesketchum** [comment]
Thanks Chris! There's an associated link in [sbncode#3](https://github.com/SBNSoftware/sbncode/issues/3) for the repo area. I'll add a comment on status there.

On your above comments, think we talked over slack, but can continue convo here if we need. I think at minimum an sbnobj repo would be good, but maybe we try to resist pulling too much out beyond that.

**Comment by wesketchum** [comment]
#10 from @PetrilloAtWork is a duplicate of this issue. I'm closing that one and keeping this one. Gianluca had the following comment at that issue:

> A repository sbnobj is needed hosting data products.
This issue is for the creation of the empty GIT/cetbuildtools based repository.
>
>I think the dependencies should be either on lardataobj or with the same as nusimdata.

**Comment by cjbackhouse** [comment]
sorry, I commented on the wrong issue earlier.

https://github.com/SBNSoftware/sbncode/issues/3 is about the CVMFS space, but we also need to create it in github and set it up as part of the build.

**Comment by wesketchum** [comment]
I think I can do the github creation and try to give it a skeleton to work from ... let met give that a go right now.

**Comment by wesketchum** [comment]
OK, initial repo with lardataobj dependency is in SBNSoftware/sbnobj#1.

**Comment by wesketchum** [comment]
Done, and part of the new releases. Closing.
