### ISSUE TITLE
Printout in Flash Match module

### ISSUE THREAD

**Issue by brucehoward-physics** [SBNSoftware/sbncode#204]
Seeing this printout at least in v09_36_00 `icaruscode`. Tagging @ikatza but if you're not the right person, can you tag who it should go to (if you know)?

```
%MSG-e FlashPredict:  FlashPredict:fmatchCryoE@Construction  22-Nov-2021 12:31:39 CST ModuleConstruction
Provided driftDistance: 149.115 is different than expected: 149.115
%MSG

**Comment by ikatza** [comment]
I'm the right person. Not really an issue, as you see the distance is the same, it's just a floating point comparison thing. I'll handle it eventually.

**Comment by wesketchum** [comment]
Well, long time to come back to it, but @ikatza has this been fixed?

**Comment by ikatza** [comment]
Soon. 

I have a PR with the fix, but I need to create and update the ICARUS files to be able to merge it.

**Comment by ikatza** [comment]
By the way https://github.com/SBNSoftware/sbncode/pull/300 fixes this issue.
