### ISSUE TITLE
sbncode is missing c7 builds

### ISSUE THREAD

**Issue by vitodb** [SBNSoftware/sbncode#29]
While testing SBND CI workflow using sbndcode from CVMFS, I found out that sbncode is missing the c7 build.
In the updated CI workflow the CI will build sbncode for c7 itself, so this is no more an issue for the CI, but users could still require it.

**Comment by vitodb** [comment]
@wesketchum, from a chat with @ascarff we figured out that to be able to exercise CI builds for c7, ups/product_deps needs to include support for c7 compiler.
This will allow the CI to build and test sbncode for c7 on its own, until then CI builds for c7 will continue to fail.

**Comment by wesketchum** [comment]
Added in this commit: https://github.com/SBNSoftware/sbncode/commit/be7d5d75dbe3f605f48965dac03a733ed6e03805

(and a similar commit for sbnobj). Hopefully all good now! Closing...
