### ISSUE TITLE
Define CVMFS location(s) for common sbn software products

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbncode#3]
@cjbackhouse brought this up in a slack channel: we don't have an obvious place to put common SBN software productions, like a SBN CVMFS area? For the moment, can request to publish all areas, but we should define the proper area(s) for this as part of the repository restructuring.

**Comment by wesketchum** [comment]
ServiceDesk ticket issues for a common CVMFS area.

**Comment by wesketchum** [comment]
This is Service Desk Ticket RITM0975699. Still in progress: OSG folks have been unusually slow to respond. But, all the prereqs on our side are complete.

**Comment by cjbackhouse** [comment]
Looks from the ticket like this has happened. And I can ls `/cvmfs/sbn.opensciencegrid.org`
Who will be the day-to-day manager of this area? (who/how should I be asking for products to be installed there?)

**Comment by wesketchum** [comment]
Yes!

Instructions for access from ticket here:

>So, Wes, you can start publishing in oasiscfs.fnal.gov.
>The local user that you have to log in as is cvmfssbn and currently you are the only person who can become cvmfssbn.
>You can add (or delete) more publishers from your experiment(s) in /home/cmvfssbn/.k5login.

@cjbackhouse I need your kerberos username, and I'll add you to the k5login. I've added Andrew, Gianluca, Tracy, Gennadiy, Joseph, Gray, and myself so far. Can add others as needed.

**Comment by cjbackhouse** [comment]
Apologies, apparently github didn't notify me about this.
My kerberos principal is "bckhouse" (no "a").

**Comment by wesketchum** [comment]
No worries. You've been added to the k5login: please test and see if you can login with the above instructions.

**Comment by wesketchum** [comment]
This has been done, to my knowledge. Closing.
