### ISSUE TITLE
Saving entire range of calo points in CAFs to split track in CAF level [release/SBN2023A_NuMI]

### ISSUE THREAD

**Issue by jedori0228** [SBNSoftware/sbncode#436]
For the on-going ICARUS NuMI xsec analysis, we want to save all calo points in CAFs to emulate the track-splitting in CAF level using ISyst. We can adjust the existing parameters in CAFMaker: https://github.com/SBNSoftware/sbncode/blob/1bd88bce24935392acc107e9f4f2d69b4a8dc0b4/sbncode/CAFMaker/CAFMakerParams.h#L405-L415

**Comment by brucehoward-physics** [comment]
Can add
```
physics.producers.cafmaker.TrackHitFillRREndCut: 9999999
```
to our CAFMaker fhicl. Once we have the combined icaruscode release proposal shortly, let's make sure we have a stage1 and/or cafmaker fhicl ready to go and it can have this added. Unless this adds too much space in which case we might a version with and a version without this change.

**Comment by brucehoward-physics** [comment]
Moving this to a "APPROVED" as it's just going to be adding a fhicl switch. If the file sizes are too large, we'll have to find another place to store them. But as long as we commit a fhicl with this updated setting.
