### ISSUE TITLE
Geant4 Physics List

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbncode#453]
With PR #435 we switched to a new high-precision (HP) physics list. We should make the old and new ones both available so we can switch between the two as needed.

Plan is to keep `SBN_QGSP_BERT_NNC` to be the old one (so would need to be reverted) and create a new one with name `SBN_QGSP_BERT_HP_NNC` which contains the HP one.

This will require both SBND and ICARUS to point to the new list here:
- SBND: [https://github.com/SBNSoftware/sbndcode/blob/252d833fd3849b82fcbbe7879870daecffe193a2/sbndcode/LArG4/larg4_services_sbnd.fcl#L11](https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/LArG4/larg4_services_sbnd.fcl#L11)
- ICARUS: https://github.com/SBNSoftware/icaruscode/blob/ffa6d4167b9d44f86c1e79300e1c646c4eb730ce/fcl/g4/larg4_services_icarus.fcl#L11

**Comment by marcodeltutto** [comment]
Looking into this, I had the following question: why are we not using Geant4's official `QGSP_BERT_HP` instead of creating our own? I think it would be better to use an official Geant4 physics unless there is motivation for changing it. @linyan-w do you think it's okay if we use `QGSP_BERT_HP`?

I see that QGSP_BERT_HP differs from the current list in the following:
- has the additional G4RadioactiveDecayPhysics
- has the additional G4IonElasticPhysics
- used G4HadronElasticPhysicsVI instead of G4HadronElasticPhysicsHP

**Comment by linyan-w** [comment]
I was following the convention in `SBN_QGSP_BERT_NNC`. 
I have no objection to the official `QGSP_BERT_HP` physics list. @sjgardiner may have more thoughts there?

**Comment by marcodeltutto** [comment]
Then @Li-Jiaoyang97 I think we should revert `SBN_QGSP_BERT_NNC` to what it was originally, and then switch sbndcode and icaruscode to use `QGSP_BERT_HP` in the two places I mentioned above. Thanks!

**Comment by Li-Jiaoyang97** [comment]
Hi @marcodeltutto, sorry I think I completely missed this message last week. I will start to restore `SBN_QGSP_BERT_NNC` to what it was originally. Moerover, related to the usage `QGSP_BERT_HP` as default, do we need to do more test to confirm the CPU and wall time to confirm it is not too time-consuming? for both SBND and ICARUS case? Thank you!

**Comment by marcodeltutto** [comment]
Sounds good @Li-Jiaoyang97. Yes, I think including a CPU and time performances from a standard g4 job is useful! You can still make the PR to switch to `QGSP_BERT_HP` as this physics list is the preferred one and we should assume we are switching to this list. You can include the performances in the PR. If later on we think this is unbearable, we can consider switching back to `SBN_QGSP_BERT_NNC`.
