### ISSUE TITLE
sbncode does not build standalone, it requires sbnobj to be checked out too

### ISSUE THREAD

**Issue by jzennamo** [SBNSoftware/sbncode#48]
When one tries to build only sbncode the build crashes here:

`/sbnd/app/users/jaz8600/ChrisTest/srcs/sbncode/sbncode/LArRecoProducer/CRTHitConverter_module.cc:22:10: fatal error: sbnobj/Common/CRT/CRTHit.hh: No such file or directory
 #include "sbnobj/Common/CRT/CRTHit.hh"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [sbncode/sbncode/LArRecoProducer/CMakeFiles/sbncode_LArRecoProducer_CRTHitConverter_module.dir/CRTHitConverter_module.cc.o] Error 1
make[1]: *** [sbncode/sbncode/LArRecoProducer/CMakeFiles/sbncode_LArRecoProducer_CRTHitConverter_module.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

this is overcome by also checking out sbnobj, but it would be nice if that wasn't necessary.

**Comment by cjbackhouse** [comment]
is this as simple as adding `find_ups_product( sbnobj )` to the CMakelists.txt?

**Comment by wesketchum** [comment]
It is. Will be fixed as of v09_09_01 release (missing `find_ups_product` in the parent CMake)...

**Comment by wesketchum** [comment]
(commit b8d3cd0657b48d43a10eca0ee4ca4fea8d26983e, if one needs to pull it separately...)
