### ISSUE TITLE
Example CAF scripts do not run

### ISSUE THREAD

**Issue by etyley** [SBNSoftware/sbncode#54]
The example scripts in [anademo](https://github.com/SBNSoftware/sbncode/tree/develop/sbncode/SBNAna/anademo) do not run. I get the following error:
```In file included from /sbnd/app/users/etyley/cafs/localProducts_larsoft_v09_09_01_e19_prof/sbncode/v09_09_01/include//sbncode/CAFAna/Core/Cut.h:10:
/sbnd/app/users/etyley/cafs/localProducts_larsoft_v09_09_01_e19_prof/sbncode/v09_09_01/include//sbncode/CAFAna/Core/Var.h:12:10: fatal error: 'StandardRecord/Proxy/FwdDeclare.h' file not found
#include "StandardRecord/Proxy/FwdDeclare.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error in <ACLiC>: Dictionary generation failed!
```

**Comment by cjbackhouse** [comment]
Fixed by
https://github.com/SBNSoftware/sbncode/commit/99a7a6b70b68939cea0429adbefa31706929c847
(merged into develop)

I expect there are other problems with the demos at the moment, given how much the CAFs have changed. CAFAna can read the current files, but there's no proper support for the spill-by-spill layout.

**Comment by etyley** [comment]
Okay great, I will test it out. 

When you say `no proper support` do you mean the `Cuts` and `Vars` or something deeper?

**Comment by cjbackhouse** [comment]
Right. You should be able to make a macro that runs, and nothing will be broken per se, but Cuts and Vars will be passed entire StandardRecords, representing spills, whereas you really want to be classifying slices if you want to fill one entry per neutrino candidate into a Spectrum.

**Comment by etyley** [comment]
Okay, so I guess I can run some tests for events without cosmics where, generally, there should be a single slice.

I assume someone is working/planning to work on this?

**Comment by cjbackhouse** [comment]
Yeah, I hadn't realized the CAFs were so far along in this transition.

**Comment by mendezdpatricia** [comment]
@cjbackhouse , does each var and cut definition has to be changed to work spill by spill, but still getting all the slices, or does the change have to come from upstream? I'd like to start seeing if I can do something about it, or wait until more expert hands work on it.

**Comment by cjbackhouse** [comment]
The plan is to make SpectrumLoader hand you slices rather than spills, so that for most analysis code it is as if we had slice-by-slice files again. What I haven't figured out is exactly how best to provide access to global spill info (like `hdr`).
