### ISSUE TITLE
Remove from `sbncode` dependencies on `icaruscode` and `sbndcode` (and related packages).

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbncode#6]

**Comment by cjbackhouse** [comment]
I tried removing the icaruscode dependency in the most obvious way (removing it from `ups/product_deps` and a couple of other places in the makefiles).

One problem I ran into was that buildtool was no longer in my path. Apparently we get that via some sequence of steps from icaruscode and from nowhere else? Running `setup cetbuildtools v7_13_02` seems to make that work. Should we add that explicitly to `product_deps` or is there some higher-level dependency we ought to have that should be picking that up?

With that, everything built...
I'm not sure how that can be, given several references in `sbnanalysis/ana/SBNOscReco/`

**Comment by PetrilloAtWork** [comment]
MRB setup can be temperamental... if you have a branch I can test, I can take a look.
Chances are that in a new environment it works.
Or not.

**Comment by cjbackhouse** [comment]
I just pushed feature/nodep_icaruscode

**Comment by PetrilloAtWork** [comment]
Works for me, after setting up the proper UPS areas (ICARUS, SBND... and MicroBooNE?!).

**Comment by PetrilloAtWork** [comment]
Checked out `sbncode` only, `feature/nodep_icaruscode` branch.
After setting up all needed UPS databases (ICARUS, SBND... and MicroBooNE?!), compilation works just fine.

**Comment by cjbackhouse** [comment]
OK, working for me now too...

I have
`source /cvmfs/uboone.opensciencegrid.org/products/setup_uboone.sh
setup uboonecode v08_47_00 -q e19:prof
source /cvmfs/sbnd.opensciencegrid.org/products/sbnd/setup_sbnd.sh
setup sbndcode v08_47_00 -q e19:prof
unsetup larbatch`
So, no icarus. Haven't explored what the rest is doing.

The reason the sbnanalysis stuff wasn't showing up is that for some reason I don't understand it's not part of the regular build system.

`cd srcs/sbncode/sbnanalysis
mkdir build
cd build
cmake ..
make`
shows the problem. I will file another issue.

**Comment by cjbackhouse** [comment]
https://github.com/SBNSoftware/sbncode/issues/7

**Comment by PetrilloAtWork** [comment]
`icaruscode` depends on the following packages: `genie_xsec`, `guideline_sl`, `fftw` and `sbndaq_artdaq_core`.
Do we know if any of these dependencies will be moved to `sbncode`?
I think at least `genie_xsec` former _should_.

**Comment by cjbackhouse** [comment]
It seems like we didn't require them in practice? Why add any dependency we don't (yet) need?

**Comment by PetrilloAtWork** [comment]
GENIE cross sections are needed only at run time, as far as I know, so nothing _formally_ depends on then. The reason to add them in a common repository is to enforce a consistent cross section version. Whether that is a good reason is open to discussion.
I suppose that sooner or later `sbndcode` _will_ depend on `sbndaq_artdaq_core`, but until then if the preference is to leave it in `icaruscode` only, that's fine with me (also I don't know if the two experiments should be bound to the same version).
I believe the other two dependencies can be moved later as needed without any issue.

**Comment by mroda88** [comment]
Hi Gianluca, just a minor comment. You are right, the genie cross sections are needed to set the tune. It's technically not the only way: one can also set up a proper environmental variable. I admit I don't know what is the better approach: it's the usual freedom vs safety. I tend to lean on the infrastructure written by Robert when in doubt, which is adding the cross sections as a dependency. If you have doubts pop a message :-)

**Comment by cjbackhouse** [comment]
OK, I agree that using environment variables only for this is bad. That's a great way to have to dig through old grid submission scripts and suffer a lot of uncertainty, vs just setting up the old release and seeing what you get.

**Comment by PetrilloAtWork** [comment]
FYI, I have merged this branch in my parallel attempt with `feature/repositoryRestructuring` (except that I retained the newer version of LArSoft from that branch). The difference is that my branch is focussed on the move of code to `sbnobj`, while this one is focused on the inversion of dependencies.

**Comment by PetrilloAtWork** [comment]
Given the comments and the status, I am:

1. detach the question on `genie_xsec` as a separate, non-blocking issue
2. closing this issue as completed
