### ISSUE TITLE
CAF duplicated reco in slc missing information

### ISSUE THREAD

**Issue by etyley** [SBNSoftware/sbncode#60]
The duplication of the `trk` and `shw` branches within the `slc` branch (added [here](https://github.com/SBNSoftware/sbncode/commit/3e6ebb0db79c75b90d8e4e36a68e23d55eb09bc4)) is incomplete as the shower energy and dEdx are not filled whilst they are filled in the original `rec` branch. The `daughters` branch is filled in neither the `trk` or `shower` branches.

**Comment by cjbackhouse** [comment]
It's pretty clear from the code that these have to get filled correctly.

I think you're running into ROOT's bizarre limitations with multiply-nested vectors. Once you get beyond two levels it likes to tell you things are zero.

The solution to this is probably to use flatcafs. The FlatMaker module can run after CAFMaker, or you can use the `convert_to_flat` executable. The resulting files behave exactly the same in CAFAna, but avoid this problem and ought to be faster to read.

**Comment by mendezdpatricia** [comment]
I see that `convert_to_flat` requires `sbncode/FlatMaker/FlatRecord.h` but I do not find it in sbncode, is it actually needed and should it be ported from other location?

**Comment by cjbackhouse** [comment]
Discussed FlatMaker offline. I think this is all understood / resolved.
