### ISSUE TITLE
shw.energy, shw.dEdx and FlatCAFs

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbncode#62]
We have a little bit of a mess with the flatcafs that needs to be straightened out.

Due to my oversight, `convert_to_flat` wasn't propagating the POT information until this morning, so Gray will have to remake the MCP2020A flatcaf file. Sorry!

While looking into doing that myself, I ran into a bit of a complication with `reco.shw.energy`. Due to the nested-vectors fiasco, this array was inaccessible straight from ROOT. One of the motivations for flatcafs is to get access to it, and things like it.

As a temporary workaround, Diana added 3 non-vector fields containing this information, and likewise with `dEdx`, and commented out the vector.

Unfortunately, this means that code running from develop expects these fields in Gray's file, which predates them. Even though they would be able to read just fine from the vector in the flatcaf. Similarly, `convert_to_flat` in development is going to choke on the absence of these fields. It would have to be run in whatever revision was used to make the original CAF. But the resulting file will still be hard to read from development.

I think the best solution is to reinstate the proper array, and also leave the individual variables in place, duplicating the information, alongside for now, and then regenerate CAFs and FlatCAFs. That gives all versions the best chance to access what they're expecting. If/when we wind up in a world where the flatcafs are universal then we can safely remove the duplicates.

**Comment by mendezdpatricia** [comment]
Pushed commit 376bde3 to address this.

**Comment by cjbackhouse** [comment]
I believe this is all now ancient history and resolved.
