### ISSUE TITLE
Integrate CI Validation into pull-requests

### ISSUE THREAD

**Issue by jzennamo** [SBNSoftware/sbncode#69]
When a pull-request is issued trigger a CI validation and have the results of that validation be reported back on the pull-request to enable a rapid validation of code changes

**Comment by vitodb** [comment]
Currently PRs are tested with a set of two regression test suites `single` and `nucosmics` workflows. Results are reported as comments to the PR.

For Physics validation, that is performed through grid jobs to process an adequate number of events, requires a grid proxy. Currently we don't have a secure way to provide the proxy for a CI build that is triggered through a GitHub PR.
For this case we can require the users that open the PR, or who is reviewing the PR to manually trigger to CI validation build that performs Physics validation, at least for PR that requires this test.
@henrylay97 put together this [CI validation wiki page](https://sbnsoftware.github.io/sbndcode_wiki/CI_Validation.html) with details.

**Comment by jzennamo** [comment]
I claim that this is integrated, what do others think? @wesketchum @vitodb @chilge

**Comment by vitodb** [comment]
> I claim that this is integrated, what do others think? @wesketchum @vitodb @chilge

I second Joseph.
