### ISSUE TITLE
sbnanalysis shouldn't depend on icaruscode/sbndcode

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbncode#7]
As part of the "normal hierarchy" work on sbncode, I notice that `sbncode/sbnanalysis` depends on various icaruscode and sbndcode paths.

What is the plan for all of this code?

**Comment by gputnam** [comment]
We can probably just remove the sbnanalysis code from the develop branch -- it's going to be ported into the new CAF file stuff anyway.

A bigger problem is the data products which are still defined in sbndcode/icaruscode. I believe it is mostly the CRT data products. The SBN-CAF file maker needs access to these data products to work. So I believe they need to be moved out of sbndocde/icaruscode into something like sbn-obj.

**Comment by cjbackhouse** [comment]
Where is the CAF stuff envisioned to live?

**Comment by cjbackhouse** [comment]
https://github.com/SBNSoftware/sbncode/issues/9

**Comment by gputnam** [comment]
Currently it's on the feature/sbncaf branch in the sbncode/ directory. At some point it should just be merged onto develop.

**Comment by cjbackhouse** [comment]
Ah, you mean that CAF will remain part of sbncode, and absorb whatever functionality sbnanalysis currently has, but rewriting it in such a way that it no longer has explicit dependencies on sbndcode/icaruscode, so that it's safe to remain as part of the re-located sbncode?

**Comment by cjbackhouse** [comment]
I think a situation of NH sbncode, but the CAF development branch remaining IH for a while sounds *extremely* confusing. Can we try and synchronize those fixes, or merge CAF into develop before the switch?

**Comment by PetrilloAtWork** [comment]
Opened issue #10 to create `sbnobj`.

**Comment by gputnam** [comment]
Yeah Chris I agree that we should try to merge the SBN CAF changes into develop before doing the switch. I don't know if there are still issues with merging onto develop (@FernandaPsihas ?). 

Once it's on develop, we can work out what changes need to be made. I think(?) it should mostly just be putting the necessary data products in an sbn-obj repo.

**Comment by PetrilloAtWork** [comment]
I am hitting this as well now.
I don't understand which is the envisioned solution, but it appears to me that `sbnanalysis` is going to keep its dependency on `icaruscode`, since it seems to use detector geometry via `geo::GeometryCore`.
Other headers that are required: `sbndcode/OpDetSim/sbndPDMapAlg.h`, `icaruscode/CRT/CRTProducts/CRTChannelData.h`. These are not scheduled for move in `sbncode`/`sbnobj` as of now.

**Comment by gputnam** [comment]
Yeah the code in sbnanalysis needs to be ported to the new structure. For now, I think it'd be ok to just comment out building (e.g.) SBNOscReco.

**Comment by wesketchum** [comment]
OK, not that this is urgent, but I want to ping on this. Can we get a time estimate for when we need this?

**Comment by wesketchum** [comment]
@gputnam : this is now well obsolete, yes? If so can you close this issue?

**Comment by wesketchum** [comment]
@PetrilloAtWork @FernandaPsihas @miquelnebot 

Is this obselete? Would be good to close.

**Comment by wesketchum** [comment]
I'm closing.
