### ISSUE TITLE
Bad Version: sbnobj 1.70.0 is less than minimum required version 1.50

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbncode#86]
Building `icaruscode` `v09_15_00` I encountered the following CMake error:
```
CMake Error at /cvmfs/larsoft.opensciencegrid.org/products/cetbuildtools/v7_17_01/Modules/CheckUpsVersion.cmake:142 (message):
  Bad Version: sbnobj 1.70.0 is less than minimum required version 1.50
Call Stack (most recent call first):
  /cvmfs/larsoft.opensciencegrid.org/products/cetbuildtools/v7_17_01/Modules/FindUpsPackage.cmake:161 (_check_version)
  /cvmfs/sbn.opensciencegrid.org/products/sbn/sbncode/v09_15_00/slf7.x86_64.e19.prof/lib/sbncode/cmake/sbncodeConfig.cmake:192 (fi
nd_ups_product)
  /cvmfs/larsoft.opensciencegrid.org/products/cetbuildtools/v7_17_01/Modules/FindUpsPackage.cmake:38 (find_package)
  /cvmfs/larsoft.opensciencegrid.org/products/cetbuildtools/v7_17_01/Modules/FindUpsPackage.cmake:157 (_use_find_package)
  icaruscode/CMakeLists.txt:63 (find_ups_product)
```
I can't fully understand what's happening, but I drop here a point: as far as I know, specifying a minimum version in `find_ups_products()` macro (like in SBNSoftware/sbncode:CMakeLists.txt) is not necessary; now I find it actually deleterious.
I have solved it locally by checking out `sbncode` in my working area and removing version requirements.

P.S. That `CMakeLists.txt` appears to also be missing the inclusion of `$ENV{ART_DIR}/Modules`.

**Comment by cjbackhouse** [comment]
Does `1.50` need to be `1.50.0`?

**Comment by PetrilloAtWork** [comment]
That's one question. Another is where that version number comes from.
I haven't noticed anything even remotely close to `1.70.0`.
That's why I would use the sledgehammer and get rid of those versions.

**Comment by wesketchum** [comment]
@PetrilloAtWork you updated CMake files a bit ago ... is this now fixed?

**Comment by wesketchum** [comment]
@PetrilloAtWork believe this is fixed ... let me know if we should reopen.
